Update git pre-commit hook, build-run

diff --git a/build-run b/build-run
--- a/build-run
+++ b/build-run
@@ -23,6 +23,7 @@ do_configure=0
 flags=""
 cfg_flags=""
 test_flags=""
+git_cached_only=0
 nargs=$(($# - 1))
 i=0
 while [[ $i -le $nargs ]]; do
@@ -57,6 +58,8 @@ while [[ $i -le $nargs ]]; do
         mode=test
     elif [[ ${arg:0:10} == "--sanitize" ]]; then
         profile=${profile}.sanitize
+    elif [[ ${arg} == "--git-cached" ]]; then
+        git_cached_only=1
     elif [[ $arg == "--" ]]; then
         shift $i
         shift 1
@@ -90,6 +93,24 @@ ln -nfs $cmake_build_dir build
     echo "compiler=$compiler"
     echo "cmake_build_dir=$cmake_build_dir"
 ) >./.active_cfg.sh
+
+# Check for git_cached_only mode, stash unstaged changes
+if [[ $git_cached_only == 1 ]]; then
+  export GIT_DIR=$(git rev-parse --git-dir)
+  if [[ -s ${GIT_DIR}/unstaged.diff ]]; then
+    echo "Error: pre-existing non-zero unstaged.diff file, aborting"
+    exit 1
+  fi
+  git diff --color=never > ${GIT_DIR}/unstaged.diff
+  # Add untracked files
+  (for file in $( git ls-files --others --exclude-standard ); do
+    git diff --color=never --no-index /dev/null $file || true
+  done ) >> ${GIT_DIR}/unstaged.diff
+  if [[ -s ${GIT_DIR}/unstaged.diff ]]; then
+    git apply -R ${GIT_DIR}/unstaged.diff
+    trap "git apply ${GIT_DIR}/unstaged.diff && rm ${GIT_DIR}/unstaged.diff || true" 0
+  fi
+fi
 
 rv=0
 # Configure
